server:
  port: 80
  context-path: /sell
logging:
  level: debug
spring:
  datasource:
    url: jdbc:mysql://192.168.1.103:3306/DCXT?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    password: 452471
    username: root
mybatis:
    type-aliases-package: com.hzm.domian
    configuration:
      lazy-loading-enabled: true
      aggressive-lazy-loading: false
