server:
  port: 80
  context-path: /sell
logging:
  level:
   com.hzm.dao: debug
spring:
  datasource:
    url: jdbc:mysql://192.168.1.17:3306/DCXT?useSSL=false&useUnicode=true&characterEncoding=utf8&?serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    username: root
mybatis:
    type-aliases-package: com.hzm.domian
    configuration:
      lazy-loading-enabled: true
      aggressive-lazy-loading: false
pagehelper:
  helper-dialect: mysql